<?php

/**
 * @file
 * Contains domain_hreflang.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\domain_hreflang\HreflangHelper;

/**
 * Implements hook_help().
 */
function domain_hreflang_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the domain_hreflang module.
    case 'help.page.domain_hreflang':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Outputs hreflang meta tags per domain.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function domain_hreflang_page_attachments(array &$attachments) {
  
  // Always output tags for all domains for front page and taxonomy terms.
  if (\Drupal::service('path.matcher')->isFrontPage() || \Drupal::routeMatch()->getParameter('taxonomy_term')) {
    $domains = \Drupal::service('domain.loader')->loadMultiple();
    foreach ($domains as $domain) {
      $hreflang = $domain->getThirdPartySetting('domain_hreflang', 'hreflang');
      if ($hreflang) {
        $attachments['#attached']['html_head'][] = HreflangHelper::addTag($domain->getUrl(), $hreflang, 'hreflang_' . $domain->id());
      }
    }
  }

  // Output tags when a node is assigned to more than one domain.
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $values = $node->get('field_domain_access')->getValue();
    if (count($values) > 1) {
      foreach ($values as $value) {
        $domain = \Drupal::service('domain.loader')->load($value['target_id']);
        $hreflang = $domain->getThirdPartySetting('domain_hreflang', 'hreflang');
        if ($hreflang) {
          $attachments['#attached']['html_head'][] = HreflangHelper::addTag($domain->getUrl(), $hreflang, 'hreflang_' . $domain->id());
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function domain_hreflang_form_domain_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $domain = $form_state->getFormObject()->getEntity();
  
  $form['hreflang'] = [
    '#type' => 'select',
    '#title' => t('Hreflang'),
    '#options' => HreflangHelper::getLangCodes(),
    '#empty_option' => t('- None -'),
    '#default_value' => $domain->getThirdPartySetting('domain_hreflang', 'hreflang'),
  ];
  
  $form['#entity_builders'][] = 'domain_hreflang_form_builder';
}

/**
 * Entity builder for Domain entities.
 */
function domain_hreflang_form_builder($entity_type, \Drupal\domain\Entity\Domain $domain, &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if ($form_state->getValue('hreflang')) {
    $domain->setThirdPartySetting('domain_hreflang', 'hreflang', $form_state->getValue('hreflang'));
    return;
  }
 
  $domain->unsetThirdPartySetting('domain_hreflang', 'hreflang');
}
